# based on https://github.com/mattermost/docker/blob/1f2adc1aebc75ed2ceb12a05c5d05c1e0298966a/docker-compose.yml (Apache License 2.0 by Mattermost)
services:
  postgres:
    image: postgres:13
    restart: always
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost

  mattermost:
    image: mattermost/mattermost-team-edition:release-7.8
    restart: always
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    tmpfs:
      - /tmp
    ports:
      - ${APP_PORT}:8065
    volumes:
      - ${MATTERMOST_DATA_PATH}/config:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}/data:/mattermost/data:rw
      - ${MATTERMOST_DATA_PATH}/logs:/mattermost/logs:rw
      - ${MATTERMOST_DATA_PATH}/plugins:/mattermost/plugins:rw
      - ${MATTERMOST_DATA_PATH}/client/plugins:/mattermost/client/plugins:rw
      - ${MATTERMOST_DATA_PATH}/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      TZ: Asia/Tokyo
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes
      MM_SERVICESETTINGS_SITEURL: ${MM_SERVICESETTINGS_SITEURL:?}
    depends_on:
      - postgres
